openapi: "3.0.1"
info:
  title: "Teste_Documento"
  description: "API de aquisição de entidades da Ramada."
  version: "2024-11-27T20:01:42Z"
servers:
- url: "https://i3sg1dcul8.execute-api.us-east-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "Dev"
tags:
- name: "Categorias"
  description: "Recurso relacionado a busca de categorias."
- name: "ProductsGrade"
  description: "Recurso que padroniza a entidade de produto para ser exibida em grade."
- name: "Parametros"
  description: "Recurso relacionado a busca de parâmetros."
paths:
  /Categorias:
    get:
      tags:
      - "Categorias"
      summary: "Adquire Categorias de Produto"
      description: "Retorna todas as categorias com sub-categorias de produtos da\
        \ Ramada."
      responses:
        "500":
          description: "Erro de Servidor"
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ResponseErrorText"
        "200":
          description: "Categorias retornadas com sucesso"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseCategoriasBody"
  /ProductsGrade:
    get:
      tags:
      - "ProductsGrade"
      summary: "Adquire Produtos Agrupados em Grade"
      description: "Retorna produtos padronizados para exibição em grade."
      parameters:
      - name: "taxajuro"
        in: "query"
        description: "Taxa de juros do tipo de negociação ativo pelo cliente. Sem\
          \ o envio desse parâmetro, produtos retornaram com os impostos zerados."
        schema:
          type: "string"
      - name: "codtab"
        in: "query"
        description: "Código da tabela de preços. Sem o envio desse parâmetro, produtos\
          \ retornaram com preço e impostos zerados."
        schema:
          type: "string"
      - name: "codparc"
        in: "query"
        description: "Código do parceiro. Verifica se o produto foi marcado como lembrete\
          \ por esse parceiro."
        schema:
          type: "string"
      - name: "tiptaxa"
        in: "query"
        description: "Tipo de taxa do tipo de negociação ativo pelo cliente. Sem o\
          \ envio desse parâmetro, produtos retornaram com os impostos zerados."
        schema:
          type: "string"
      - name: "pagina"
        in: "query"
        description: "Realiza paginação na resposta. Se deixado em branco, retorna\
          \ o topo da paginação."
        schema:
          type: "string"
      - name: "grupo"
        in: "query"
        description: "ID da categoria dos produtos a serem retornados."
        required: true
        schema:
          type: "string"
      responses:
        "500":
          description: "Erro no Servidor"
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ResponseErrorText"
        "200":
          description: "Produtos retornados com sucesso"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseProductsGradeBody"
  /Parametros:
    post:
      tags:
      - "Parametros"
      summary: "Adquire um Parâmetro Específico"
      description: "Retorna informações de um parâmetro especificado por seu nome."
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestParametrosBody"
        required: true
      responses:
        "200":
          description: "Parâmetro retornado com sucesso"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseParametrosBody"
components:
  schemas:
    RequestParametrosBody:
      title: "RequestParametrosBody"
      required:
      - "parametro"
      type: "object"
      properties:
        parametro:
          type: "string"
    ResponseParametrosBody:
      title: "ResponseParametrosBody"
      type: "object"
      properties:
        success:
          type: "boolean"
        data:
          $ref: "#/components/schemas/ResponseParametrosBodyData"
    ResponseCategoriasBodyItemSubCatItem:
      type: "object"
      properties:
        Codgrupoprod:
          type: "integer"
        Descrgrupoprod:
          type: "string"
        CodgrupoPai:
          type: "integer"
        Imagem:
          type: "string"
        Cont_subCategorias:
          type: "integer"
    ProductModelEmbalagensItem:
      type: "object"
      properties:
        Codvol:
          type: "string"
        Qtd:
          type: "string"
        Multiplicador:
          type: "string"
    ResponseCategoriasBody:
      title: "ResponseCategoriasBody"
      type: "array"
      items:
        $ref: "#/components/schemas/ResponseCategoriasBodyItem"
    ResponseCategoriasBodyItem:
      type: "object"
      properties:
        Codgrupoprod:
          type: "integer"
        Descrgrupoprod:
          type: "string"
        CodgrupoPai:
          type: "integer"
        Imagem:
          type: "string"
        SubCat:
          type: "array"
          items:
            $ref: "#/components/schemas/ResponseCategoriasBodyItemSubCatItem"
    ResponseErrorText:
      title: "ResponseErrorText"
      type: "string"
    ResponseProductsGradeBody:
      title: "ResponseProductsGradeBody"
      type: "array"
      items:
        $ref: "#/components/schemas/ProductModel"
    ResponseParametrosBodyData:
      type: "object"
      properties:
        CodParametro:
          type: "string"
        Parametro:
          type: "string"
        Valor:
          type: "string"
    ProductModel:
      title: "ProductModel"
      type: "object"
      properties:
        Descrmarcarmd:
          type: "string"
        Codprod:
          type: "string"
        Codemp:
          type: "integer"
        Codmarcarmd:
          type: "integer"
        Destaque:
          type: "boolean"
        Codgrupoprod:
          type: "integer"
        Descrprod:
          type: "string"
        Descgrupoprod:
          type: "string"
        Compldesc:
          type: "string"
        Caracteristicas:
          type: "string"
        Agrupmin:
          type: "integer"
        Codvol:
          type: "string"
        Estoque:
          type: "integer"
        Ncm:
          type: "string"
        Referencia:
          type: "string"
        Refforn:
          type: "string"
        Altura:
          type: "number"
        Largura:
          type: "number"
        Espessura:
          type: "number"
        Shelflife:
          type: "integer"
        Promocao:
          type: "boolean"
        Queimaestoque:
          type: "boolean"
        Embalagens:
          type: "array"
          items:
            $ref: "#/components/schemas/ProductModelEmbalagensItem"
        Preco:
          type: "string"
        ProdutoST:
          type: "string"
        ProdutoIpi:
          type: "string"
        Lembrete:
          type: "boolean"
        Pesobruto:
          type: "string"
